### ISSUE TITLE
Please stop calling SMPS 'Sound-Source'

### ISSUE THREAD

**Issue by Clownacy** [NatsumiFox/AMPS#14]
I've gone over [here](https://forums.sonicretro.org/index.php?posts/965404/) why 'Sound-Source' likely isn't SMPS's name - rather, it appears to merely be a placeholder string for the name of the game that the driver is inserted in. Specifically 'Source' appears to be a corruption of 'Sorce', which is possibly short for 'Sorcerian', a game which uses SMPS Z80 and was released around the time the leaked source code is dated.

Retroactively 'correcting' SMPS to Sound-Source like this is not only potentially factually-incorrect, but also extremely confusing to anyone who only knows SMPS by its unofficial name.

**Comment by NaotoNTP** [comment]
Just to clarify some of the thought process in invalidating & closing this almost immediately, while your concern is appreciated and the theory as to why the driver would be called "Sound-source" at all may hold some water & it certainly makes sense, we see little reason to go back though and change it back, especially when there isn't really any way to confirm your theory as factual itself, and here's why:

Whether it is the official driver name or not, the fact that is was indeed announced as being that by hiddenpalace.org lead to a widespread adoption of this as fact to the point that it's already being used very interchangeably & synonymously with SMPS in conversation; the fact that you yourself felt bothered enough by it to write that Retro post & then open up an issue on here about it is a pretty obvious testament to just how common it's becoming. It's not unreasonable to assume me that the terms will be used about as frequently as each other in time, so you can consider the interchangeable use future-proofing in a sense. Believe me, Aurora herself was very skeptical of whether or not Sound-source was actually the driver name when some stuff from the eventual release was previewed a few months prior to the actual Hidden Palace release, so it's not like she just suddenly changed her mind about that for no good reason. 

As for any possible confusion related to using the Sound-source name instead of SMPS, that can and will go both ways as more people adopt Sound-source as the "official" name of the driver. But fear not: in addition to the AMPS name itself being very clearly derived from the SMPS name, there is an entire segment of the documentation explaining how the terms can be & are used interchangeably, so any confusion would essentially boil down to end-users not reading the instructions, which... doesn't really sound like it should be our problem? If you're not reading the manual to learn about how to use the driver & ways in which it is different from typical SMPS/Sound-source, I think what terminology is used for the driver that AMPS was modeled after is going to be the least of your concerns, but perhaps that's just me.

If you really feel that passionate about it, you are more than welcome to fork this & replace every instance of the Sound-source name with SMPS if you so choose, but we're going to keep it the same here.

**Comment by Clownacy** [comment]
...Labelling my issue as invalid, closing it with no response, and then telling me 'make a fork if it bothers you so much', is textbook hostile GitHub behaviour.

I didn't come here to start a flamewar - in fact, I think I was pretty respectful with my first post, so I think this treatment is unwarranted, and just making the situation worse.

I came here to talk this out, like any reasonable person. I'm glad that NatThePorcupine is meeting me halfway, but I expected the dev team as a whole to be this friendly.

```
the fact that you yourself felt bothered enough by it to write that Retro post & then open up an issue on here about it is a pretty obvious testament to just how common it's becoming.
```
No, I made that post in the first place because I saw an AMPS update post do it. I figured that Natsumi was the only person besides the Hidden Palace team calling SMPS 'Sound-Source', and wanted to stop it from spreading. I don't think it's common at all, which is why I'm trying to stop it from becoming common.

Using 'Sound-Source' because more people might recognise it is a fine-enough reason (even though I don't think anything besides this repo and Hidden Palace call it that), but saying stuff like ["its real name seems to be Sound-Source."](https://github.com/NatsumiFox/AMPS/blob/master/AMPS/AMPS%20Documentation.html#L1187) doesn't have anything to do with that - that's just directly pushing something that has next to no evidence supporting it, and a fair bit of evidence against it.

At the very least, if you don't want to stop calling SMPS 'Sound-Source', please stop trying to claim that 'Sound-Source' is SMPS's real name. Misinformation shouldn't be allowed to spread.

**Comment by Awuwunya** [comment]
I don't personally want to bother with arguing over a name that may or may not have existed 20 years ago. As the matter stands, Sound-Source was a more likely candidate for the name of SMPS, as was EasySnd earlier, too. Given what was dicussed on the thread, it seems like it might not be exactly clear whether or not that was the case, and whether or not "sorce" is a typo or not. Whether or not a real name exists, maybe we'll never find out. I don't want to spend my time arguing about it, I made the decision with the knowledge I had and it seems a reasonable assumption to make. I worded the text, knowing it was not 100% on whether or not it was the case, too. I don't see this as big enough of an issue to go back and revert everything, especially because SMPS is a community made name anyway. The document clearly says why the name confusion exists, so in the end its not a big issue.
